### ISSUE TITLE
Support basic text formatting shortcuts

### ISSUE THREAD

**Issue by 12people** [uxbox/uxbox#1229]
**Describe the solution you'd like**
When editing text, I would expect Cmd-B to make the selected text bold, Cmd-I to make it italic, and Cmd-U to underline it. (These are macOS shortcuts; other platforms would use Ctrl.) These shortcuts are standard across all competing vector editors.

**Comment by myfunnyandy** [comment]
This is something that we definitely want to do but for some reason still wasn't at our backlog. User story created and waiting to be prioritized: https://tree.taiga.io/project/penpot/us/2052?backlog-q=%5Btext%5D&no-milestone=1
Thanks!

**Comment by pabloalba** [comment]
Fixed :)

**Comment by tingeka** [comment]
@pabloalba I'm facing the same issue still. Selected text (not the element, but the content itself) can't be bolded, nor italicized or underlined. I can create a new issue if I it's needed to.

Forgot to add: this happens in both Brave Browser and Firefox, Kubuntu 23.04 (X11).

**Comment by pabloalba** [comment]
@tingeka yes, please, open a new issue with screenshots/video, so we can see the behavior. Thank you!
