### ISSUE TITLE
Missed characters and kerning problems in pdf export result (all artboards export only)

### ISSUE THREAD

**Issue by zhartus** [uxbox/uxbox#1324]
**Describe the bug**
When exporting all artboards to a multi-page pdf file, a problem arises: some letters disappear, and the kerning of all text is slightly broken (the horizontal letter spacing is slightly randomly changed).
It is noteworthy that if you export pages one by one (one page at a time), then this problem is not observed.

**To Reproduce**
1.  Create file with many artboards and texts (I used Roboto font).
2.  Main menu -> "Export artboards to PDF..."
3.  Check result PDF file.

**Expected behavior**
Obviously, the letters should not disappear and the kerning should not break. 

**Screenshots**

![image](https://user-images.githubusercontent.com/17202099/140318752-c7328a99-f36b-442b-a852-c01746c5c5fd.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   Browser Firefox
-   Version 94.0

**Environment:**
https://design.penpot.app/

**Comment by hirunatan** [comment]
This is a strange issue indeed! We'll are looking at it. Let's see if we are able to reproduce it.

Thanks for reporting.

**Comment by zhartus** [comment]
@hirunatan Thanks.
I'm not sure if the missing characters problem is easily reproducible. In my case, out of 16 pages (artboards), only 2 were affected. And it is unclear how these pages differ from the rest. I assumed that this was an accidental error during export, but I tried to export again, and the problems in the new file were in exactly the same places.

**Comment by hirunatan** [comment]
Would it be possible for you to send me the affected file? Actually, don't need the whole file, only the failing artboards. Perhaps you can duplicate the file, remove the other artboards and send the exported .penpot file to info@penpot.app. Could you please?

**Comment by hirunatan** [comment]
I have created an issue to track this: https://tree.taiga.io/project/penpot/issue/2234

**Comment by zhartus** [comment]
@hirunatan 
Done, I sent you the file by email.
Remarkably, when I left only two failing artboards, the problem went away. I experimented a bit and have found that if I leave the previous few artboards, then the problem returns again. So I sent you a file with 5 artboards. You can remove the first 3 yourself and make sure that the problem disappears after that. Perhaps this fact can help in detecting a bug.

**Comment by hirunatan** [comment]
Ok. I've been able to reproduce the problem, thanks. It seems that the tool we use to merge the pages does some over-optimizations! I'm researching for other tools, I hope to find one that is still light and more straigthforward.

**Comment by zhartus** [comment]
@hirunatan 
Ok, I'm glad you were able to reproduce the problem.
By the way, I use the pdftk utility to merge one-page pdf files to one multipage file. This is a console utility, free and open source, it is present in the repositories of most Linux distributions. If you've used something different before, you can try it.

In the simplest case, the command looks like this:
`pdftk 1.pdf 2.pdf 3.pdf cat output 123.pdf`

**Comment by zhartus** [comment]
And by the way, there is another problem with export. It also manifests itself in one-page export, and not only for PDF, but also for other options (PNG as example), so there is most likely no connection. But just in case, I'll leave a link here: https://github.com/penpot/penpot/issues/1305

**Comment by hirunatan** [comment]
Yes, pdftk is one of the tools we are considering. I have tested it, and it appears to work ok. Also pdfunite from poppler. I think any of then will be good. In the next release it should be fixed.

The other problem you say was already being worked, and today we found the cause and fixed it ;)

**Comment by zhartus** [comment]
@hirunatan Great, thank you very much for your work!

**Comment by zhartus** [comment]
Not implemented in beta yet?
Today I received a message about updating to beta, checked, but the problem is still persist. When is it planned to implement the new exporter?

**Comment by niwinz** [comment]
The fix for this has not arrived for this release. It should be fixed for the next release.

**Comment by zhartus** [comment]
@niwinz 
Okay, thank you.
