### ISSUE TITLE
Penpot does not remember that I'm logged in

### ISSUE THREAD

**Issue by jsmorabito** [uxbox/uxbox#1346]
**Describe the bug**
On both Safari and Brave browser after some time when opening a new tab or after restarting my machine, Penpot shows me the landing page when I expect my account to remain logged in.

**To Reproduce**
1.  open Penpot in a new tab
2. log in
3. close Penpot tab
4. close browser
4. open browser again
5. open Penpot In new tab
6. observe Penpot opens to landing page instead of being logged in

**Expected behavior**
Penpot to automatically log into my account after closing/reopening in a new tab or closing/reopening the browser

**Comment by niwinz** [comment]
Penpot uses session cookes for maintain the user session. The session cookes are cleared by default when the browser is closed and reopened. Are you suggesting using permanent cookies?

**Comment by jsmorabito** [comment]
> Penpot uses session cookes for maintain the user session. The session cookes are cleared by default when the browser is closed and reopened. Are you suggesting using permanent cookies?

Yes!

**Comment by hirunatan** [comment]
Please, check the url you are using to access penpot.

If you go to https://penpot.app, you always see the landing page (this is how we are configured it). But if you go to https://design.penpot.app and you were logged in before, you should access directly, without entering your password again. So the Penpot main entry point is this second address.

Does it work for you? Or still get the login screen after navigating directly to the second screen?

**Comment by jsmorabito** [comment]
> Please, check the url you are using to access penpot.
> 
> If you go to https://penpot.app, you always see the landing page (this is how we are configured it). But if you go to https://design.penpot.app and you were logged in before, you should access directly, without entering your password again. So the Penpot main entry point is this second address.
> 
> Does it work for you? Or still get the login screen after navigating directly to the second screen?

This works for me! Was this functionality already there and I've been doing it wrong this whole time?

**Comment by niwinz** [comment]
Looks like the problem is solved :tada:

**Comment by jsmorabito** [comment]
> Looks like the problem is solved 🎉

Hi, unfortunately, I am being greeted by this page in a browser that I was previously logged into, so maybe the problem isn't solved yet :/

I am going to https:/design.penpot.app on both Brave browser and Safari browser, both of which I'd been previously logged in to

![image](https://user-images.githubusercontent.com/46250921/144632813-908dba24-4fbf-4938-9f82-260f16d348ec.png)

**Comment by niwinz** [comment]
how much time passed since you last touched penpot?, Right now, if you don't connect in aprox 48 hours, the session is automatically expired. This ensures that if you use penpot every day you will be maintained loggedin but.

**Comment by jsmorabito** [comment]
@niwinz it may have been 48 hours or more... while its true that I should be using Penpot more 😁 it would be nice if this minor inconvenience could be avoided in someway. My expectation is that Penpot will remained logged in whenever I access the page through a browser that I've logged in before. I don't know the conventions followed by other applications, but maybe there is a more appropriate session expiration time? For my use case, I use Penpot at non consistent time intervals, usually to make a quick change to a design or to quickly ideate. I do not always log in every day...and it seems in this instance I had not for 2 days xD

**Comment by niwinz** [comment]
thnks @jsmorabito for the feedback, we will consider incrementing this timeout for the next release, I will ask the same question internally for get more feedback on this and make the correct decision.

**Comment by jsmorabito** [comment]
![image](https://user-images.githubusercontent.com/46250921/146971528-6db96362-6e6e-4c54-b69d-5d5a377a1361.png)

"Remember me for 30 days" could be another option
