### ISSUE TITLE
Docker / penpot_penpot-backend_1: no ports opened, frontend could not connect

### ISSUE THREAD

**Issue by JackHewson** [uxbox/uxbox#1548]
**Describe the bug**
No backend ports are opened in docker self-hosted version, which results in frontend errors (see details below).

**To Reproduce**
1.  Download penpot docker files as described in https://help.penpot.app/technical-guide/getting-started/
```
wget https://raw.githubusercontent.com/penpot/penpot/main/docker/images/docker-compose.yaml
wget https://raw.githubusercontent.com/penpot/penpot/main/docker/images/config.env
```
2. run the container
```
docker-compose -p penpot -f docker-compose.yaml up -d
```` 
3.  Check the running containers
``` 
364f94b06c2f   penpotapp/frontend:latest            "/bin/bash /entrypoi…"   7 minutes ago   Up 7 minutes    0.0.0.0:9001->80/tcp, :::9001->80/tcp   penpot_penpot-frontend_1
995ac3e66235   penpotapp/backend:latest             "/bin/bash run.sh"       7 minutes ago   Up 7 minutes                                            penpot_penpot-backend_1
456ad8bf622a   postgres:13                          "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes    5432/tcp                                penpot_penpot-postgres_1
6230c38f3775   penpotapp/exporter:latest            "/usr/local/nodejs/b…"   7 minutes ago   Up 7 minutes                                            penpot_penpot-exporter_1
8b7a26cc2de9   redis:6                              "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes    6379/tcp                                penpot_penpot-redis_1
``` 

4.  Open the url: `http://10.0.0.2:9001`

**Expected behavior**
PenPot login is shown.

**Desktop (please complete the following information):**

-   OS: Windows 10 
-   Browser: Firefox
-   Version: 96

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: Ubuntu 20.04 LTS

Also provide Docker commands or docker-compose file if possible and if proceed.x

-   Docker / Docker-compose Version:  Docker Version:  20.10.9 / docker-compose version 1.29.2, build 5becea4c

-   Image: (see above)

**Frontend Stack Trace (if self-hosted)**

<details>

```
8#8: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.1, server: _, request: "GET /api/rpc/query/profile HTTP/1.1", upstream: "http://172.18.0.5:6060/api/rpc/query/profile", host: "10.0.0.2:9001"
```

</details>

**Backend Stack Trace (if self-hosted)**

<details>

```
 I app.http.session - action="initialize session updater" max-batch-age="PT5M" max-batch-size="200"
 I app.http - host="localhost" msg="starting http server" name="http" port="6060"


(...)

I app.worker - action="start worker" name="worker" queue="default"
I app.srepl - host="127.0.0.1" msg="initializing server repl" name="main" port="6062"
I app.main - msg="welcome to penpot" version="1.11.0-beta-6445-g7710ffcbf"


```

</details>

**Comment by dploeger** [comment]
I believe this is, because the backend is only listening to localhost:

```
root@ea8e110691f8:/opt/penpot/backend# netstat -nlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:6060          0.0.0.0:*               LISTEN      1/java
tcp        0      0 127.0.0.1:6062          0.0.0.0:*               LISTEN      1/java
tcp        0      0 127.0.0.11:33951        0.0.0.0:*               LISTEN      -
udp        0      0 127.0.0.11:55549        0.0.0.0:*                           -
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
```

**Comment by JackHewson** [comment]
> I believe this is, because the backend is only listening to localhost:

But it should map itself outside, to be reachable for the other containers, right?
I'm asking, if I'm doing something wrong.

**Comment by dploeger** [comment]
No, it doesn't need to. They share the same overlay network, so the other containers can call it without it being available from the host. I believe it needs to listen to * instead of localhost though. I'm not 100% sure there, but the backend was reachable from inside the backend container and not from the frontend container in my setup.

**Comment by niwinz** [comment]
Workaround: set `PENPOT_HTTP_SERVER_HOST=0.0.0.0` on `config.env` and restart contaieners. I will push a new image as soon as I fix some other issues on the docker images build process.

**Comment by niwinz** [comment]
New images deployed, the problem should be fixed.

**Comment by slfhstr** [comment]
Still seeing this issue, even with latest images and `PENPOT_HTTP_SERVER_HOST=0.0.0.0`

**Comment by dploeger** [comment]
@timconsidine I can't reproduce it with the latest images and without setting `PENPOT_HTTP_SERVER_HOST`

**Comment by niwinz** [comment]
> Still seeing this issue, even with latest images and `PENPOT_HTTP_SERVER_HOST=0.0.0.0`

You probably have a different issue. Feel free to open a separated issue providing context details, such that image-ids, backed logs, and describing the real issue.
