### ISSUE TITLE
bug: Can't paste images from clipboard on self-hosted PenPot

### ISSUE THREAD

**Issue by SatarisGIT** [uxbox/uxbox#2918]
### Steps To Reproduce

Steps to reproduce: 
* Self-host PenPot app using docker - do not change any default values
* Use apache2 with proxypass (using cloudflare with ssl cert. on HTTPS proto)
* Create account, create project (Draft)
* Try to copy-paste image from clipboard

This problem appear with version: 1.17.0 - it works okay with version released around 2 months ago

I also use fresh docker-compose file, fresh volumes without any data to check if maybe it is not problem with update from old version - it also not working with totally clean installation

### Expected behavior

Image will be copied to project

### Actual behavior with Screenshots

Error: 
![image](https://user-images.githubusercontent.com/28608081/217273600-d1a8b615-82d8-46da-b9f5-a9f92fca64d1.png)
![image](https://user-images.githubusercontent.com/28608081/217273807-d3f2fe86-4a74-41f4-bb2c-ca43be25fd34.png)

### Desktop (please complete the following information)
- Win 11, Chrome latest (109.0.5414.120)

### Environment (please complete the following information)
Self-hosted - Ubuntu 22.04
Docker version: 20.10.23
Compose version: v2.14.2
PenPot docker image version: 1.17.0

### Backend Stack Trace

Output from docker logs console

`penpot-penpot-backend-1   | [2023-02-07 14:49:02.457] E app.http.errors - hint="/opt/data/assets/68"
penpot-penpot-backend-1   | TRACE:
penpot-penpot-backend-1   |  →  java.nio.file.AccessDeniedException: /opt/data/assets/68 (UnixException.java:90)
penpot-penpot-backend-1   | DETAIL:
penpot-penpot-backend-1   |  →  java.nio.file.AccessDeniedException: /opt/data/assets/68 (UnixException.java:90)
penpot-penpot-backend-1   |     at: sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
penpot-penpot-backend-1   |         sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
penpot-penpot-backend-1   |         sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
penpot-penpot-backend-1   |         sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
penpot-penpot-backend-1   |         java.nio.file.Files.createDirectory(Files.java:700)
penpot-penpot-backend-1   |         java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
penpot-penpot-backend-1   |         java.nio.file.Files.createDirectories(Files.java:793)
penpot-penpot-backend-1   |         datoteka.fs$create_dir.invokeStatic(fs.clj:328)
penpot-penpot-backend-1   |         datoteka.fs$create_dir.invoke(fs.clj:321)
penpot-penpot-backend-1   |         datoteka.fs$create_dir.invokeStatic(fs.clj:323)
penpot-penpot-backend-1   |         datoteka.fs$create_dir.invoke(fs.clj:321)
penpot-penpot-backend-1   |         app.storage.fs$fn__27684$fn__27687.invoke(fs.clj:58)
penpot-penpot-backend-1   |         promesa.exec$wrap_bindings$fn__14953.invoke(exec.cljc:163)
penpot-penpot-backend-1   |         promesa.util.Supplier.get(util.cljc:34)
penpot-penpot-backend-1   |         java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
penpot-penpot-backend-1   |         java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
penpot-penpot-backend-1   |         java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
penpot-penpot-backend-1   |         java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
penpot-penpot-backend-1   |         java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
penpot-penpot-backend-1   |         java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
penpot-penpot-backend-1   |         java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
penpot-penpot-backend-1   |
penpot-penpot-backend-1   |`

**Comment by SatarisGIT** [comment]
@UPDATE For test purposes I change CHMOD to 777 on /opt dir in frontend container + chmod for volume recursively, and now I can upload new image, I can see it in volumes and can view it in file explorer, but it is not visible in project

![image](https://user-images.githubusercontent.com/28608081/217293615-0827c8f6-56a7-44b7-8362-7bd3d3c18fd4.png)

**Comment by subinznz** [comment]
same issue. I think some permission issues , console log in backend was complaining that the file could not be found , but when you browse into it it is there. I am using the latest docker-compose file

**Comment by niwinz** [comment]
Related to: https://github.com/penpot/penpot/issues/2751
The fix is almost ready, I'm building the new images right now.

**Comment by niwinz** [comment]
new images pushed, this should be fixed

**Comment by SatarisGIT** [comment]
Thanks! After set correct CHMOD to assets dir volume everything works as it should :)

**Comment by violoncelloCH** [comment]
Hi, 
I've updated to the latest release and viewing/displaying assets which are already on the server is now working again, thanks @niwinz ! However, uploading new assets still fails with a similar error as posted in this issue:
<details>
<summary>error log</summary>

```
penpot-frontend_1  | 172.16.0.20 - - [07/Feb/2023:22:02:50 +0000] "POST /api/rpc/mutation/upload-file-media-object HTTP/1.1" 500 101 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0"
penpot-backend_1   | [2023-02-07 22:02:50.633] E app.http.errors - hint="/opt/data/assets/43/ad"
penpot-backend_1   | TRACE:
penpot-backend_1   |  →  java.nio.file.AccessDeniedException: /opt/data/assets/43/ad (UnixException.java:90)
penpot-backend_1   | DETAIL:
penpot-backend_1   |  →  java.nio.file.AccessDeniedException: /opt/data/assets/43/ad (UnixException.java:90)
penpot-backend_1   |     at: sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
penpot-backend_1   |         sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
penpot-backend_1   |         sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
penpot-backend_1   |         sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
penpot-backend_1   |         java.nio.file.Files.createDirectory(Files.java:700)
penpot-backend_1   |         java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
penpot-backend_1   |         java.nio.file.Files.createDirectories(Files.java:793)
penpot-backend_1   |         datoteka.fs$create_dir.invokeStatic(fs.clj:328)
penpot-backend_1   |         datoteka.fs$create_dir.invoke(fs.clj:321)
penpot-backend_1   |         datoteka.fs$create_dir.invokeStatic(fs.clj:323)
penpot-backend_1   |         datoteka.fs$create_dir.invoke(fs.clj:321)
penpot-backend_1   |         app.storage.fs$fn__27743$fn__27746.invoke(fs.clj:58)
penpot-backend_1   |         promesa.exec$wrap_bindings$fn__15013.invoke(exec.cljc:163)
penpot-backend_1   |         promesa.util.Supplier.get(util.cljc:34)
penpot-backend_1   |         java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
penpot-backend_1   |         java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
penpot-backend_1   |         java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
penpot-backend_1   |         java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
penpot-backend_1   |         java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
penpot-backend_1   |         java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
penpot-backend_1   |         java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
penpot-backend_1   | 
penpot-backend_1   |
```
</details>

are admins expected to manually change th directory permissions to make it work again ?

**Comment by niwinz** [comment]
This command should fix the issue permanently:
```
docker exec -u 0 penpot-backend_1 chown -R penpot:penpot /opt/data
```
where the `penpot-backend_1` is the container name.

I'm still researching the cause of the permission issue, it looks like only happening on upgrading, if you run a clean new instance it works as epxected, at least on my own tests

**Comment by violoncelloCH** [comment]
so I've applied the command to change ownership given by @niwinz  in https://github.com/penpot/penpot/issues/2751#issuecomment-1422299171 and it solved my issue:

```
docker exec -u 0 penpot-backend_1 chown -R penpot:penpot /opt/data
```
uploading new assets is working again

**Comment by violoncelloCH** [comment]
thanks, this worked !

yes indeed, this seems to be due to how the permissions were set before the upgrade. Ownership before executing the command was `root:root`
