### ISSUE TITLE
bug: changing anything in file results as internal error

### ISSUE THREAD

**Issue by Robind-ev** [uxbox/uxbox#3243]
![image](https://github.com/penpot/penpot/assets/132882672/3cda9dee-7670-41c5-a2e5-a436f392f9c7)

![image](https://github.com/penpot/penpot/assets/132882672/c764bdd1-8676-4038-908a-6316f6d36b27)

![image](https://github.com/penpot/penpot/assets/132882672/9c18da77-a915-45f9-9d8a-e2d79641ebb7)

No clue what causes this, if i can do anything else let me know! 

I have the file downloaded, if i can send it to someone, let me know!

**Comment by pabloalba** [comment]
Hi!

Please, send the file to support@penpot.app and we will look into it.

Thank you!

**Comment by superalex** [comment]
Thank you very much, with your help we could detect the issue, solve it and deploy to production. Your file should be working ok now.

Sorry for the inconvenience.

**Comment by Robind-ev** [comment]
I dont mean to ruin the party, but the file is still broken on my end :sweat_smile: ? 

I run a local docker and updated using `docker compose -f docker-compose.yaml pull`

`version="1.18.3-9885-g353de39d4"` is the running version.

**Comment by superalex** [comment]
Sorry! I assumed you were using our saas, no problem, tomorrow I will release new docker versions too
