### ISSUE TITLE
bug: Crash on ungrouping objects when zoomed in

### ISSUE THREAD

**Issue by abuehrle** [uxbox/uxbox#3254]
### Steps To Reproduce

1. Group a collection of text based objects onto a panel on top of the background panel. 
2. Zoom into a section of the text using the keyboard, i.e. "CMD + "
3. Ungroup a subsection of the grouped text. 
4. System returns an internal error. 
<img width="422" alt="Screenshot 2023-05-26 at 12 40 48 PM" src="https://github.com/penpot/penpot/assets/13420383/56bcaddc-b6ea-4554-8eee-22a9003bb6d5">

### Expected behavior

Expect system to ungroup objects and not return a fatal error. 

### Actual behavior

Ungrouping the text objects when zoomed in returns an internal error: 

### Desktop (please complete the following information)

MAC OS - Ventura 13.4 (22F66)

Chrome - Version 113.0.5672.126 (Official Build) (arm64)

**Comment by superalex** [comment]
Hello @abuehrle 

Is this happening in https://design.penpot.app/?, if that's the case, could you please include the file url?

If you could also attach a video showing how to reproduce the issue it would be great.

Thanks!

**Comment by abuehrle** [comment]
Yes this is happening in the https://design.penpot.app/?: https://design.penpot.app/#/workspace/4755a563-5b43-8015-8001-f34506a92367/2a21f5ae-60ee-8151-8001-f3450b483c8b?page-id=2a21f5ae-60ee-8151-8001-f3450b483c8c&layout=layers

Here's a video that shows the issue better: 

https://github.com/penpot/penpot/assets/13420383/b9f542e9-9c4c-4702-bd4c-81f598cb1647

**Comment by superalex** [comment]
Hello @abuehrle 

We have released a new version to PRO some hours ago and I think this should be fixed. Could you please check if this is still happening?

**Comment by abuehrle** [comment]
@superalex Not sure if the hosted app has been updated or not. I'm on version 1.18, and I am still seeing this issue.

**Comment by superalex** [comment]
Hi @abuehrle I deployed this to  https://design.penpot.app/ , if are checking https://design.penpot.app/#/workspace/4755a563-5b43-8015-8001-f34506a92367/2a21f5ae-60ee-8151-8001-f3450b483c8b?page-id=2a21f5ae-60ee-8151-8001-f3450b483c8c&layout=layers could you try reloading the site clearing the cache?

**Comment by abuehrle** [comment]
I cleared the chrome browser cache for the last 24 hours, logged back into Penpot and unfortunately I am still seeing this issue. @superalex

**Comment by superalex** [comment]
Thanks @abuehrle 

That's very strange, I can't reproduce the issue now, are you doing the same action? (if you could attach another video it would be great).

One more question, if you open the javascript console, you should see a message saying "message="Welcome to penpot"... including the version and the build-date, what is it saying?

**Comment by abuehrle** [comment]
One difference I noticed is the error message takes a bit longer to appear.   Here's the build number and date and a video:  

window.penpotVersion = "1.18.4-9903-g2a1619d71";
window.penpotBuildDate = "Wed, 31 May 2023 09:17:17 +0000";

https://github.com/penpot/penpot/assets/13420383/58934a57-c827-4b05-8512-e36dd3ca7d7c

@superalex  I could send you the logs from the console if you need to see that?

**Comment by superalex** [comment]
Yes please, that would be great!

**Comment by superalex** [comment]
If you could also test with a different browser it would be very helpful too :)

**Comment by abuehrle** [comment]
@superalex here's the logs for you.  I had my colleague test it in Safari and he gets the same thing. 
[design.penpot.app-1685630061093.log](https://github.com/penpot/penpot/files/11626545/design.penpot.app-1685630061093.log)

**Comment by superalex** [comment]
Thank you very much, I'm still trying to reproduce the issue but I can't :(

If you export a .penpot file and reimport it, is this happening in the new file too?

**Comment by abuehrle** [comment]
Downloaded a .penpot file using each method, started a new project and tested. Same result on each .penpot file, sadly.  I also had a thought that maybe it has to do with my M1 chip, so tested this on my older intel machine. Same result there too. Let me know if I can try something else? @superalex

**Comment by abuehrle** [comment]
I don't know if this is related to the issue, but one thing I am noticing is that the text and the line appear skewed, even though the settings are to 0 dg rotation. The background and all other objects are also set to 0 dg rotation.

**Comment by superalex** [comment]
Thank you very much @abuehrle 

It's so strange...could you please send one of those .penpot files to support@penpot.app ?

**Comment by madalenapmelo-kp** [comment]
Hi @abuehrle,

This issue should be resolved in the last release, could you please confirm and close this issue if it is indeed resolved? 

Thanks!
