### ISSUE TITLE
bug: Drag and drop of a component into a grid layout behaves weirdly and sometimes crashes

### ISSUE THREAD

**Issue by Picorims** [uxbox/uxbox#4395]
### Steps To Reproduce

1. Drag and drop a component copy in a grid layout
2. Release the mouse once the component is in the desired cell

### Expected behavior

The component is placed correctly in the grid.

### Actual behavior

The component content is misplaced, and upon undo/redo can lead to unexpected behavior (flicking component that cannot be interacted with), and even crashes.

### Screenshots or video

https://github.com/penpot/penpot/assets/41078963/6f4c5ce6-c7ea-4bdc-a6f3-1e6f41266b19

### Desktop (please complete the following information)

- Windows 10
- Firefox 124.0.2 (64 bits)

### Environment (please complete the following information)

- https://design.penpot.app/

### Frontend Stack Trace

```console
Hint:    error on validating file referential integrity
Prof ID: 8ec95363-4e2c-80a4-8002-c4fa44578d68
Team ID: 8ec95363-4e2c-80a4-8002-c4fa44de8f06
File ID: eb74e0b5-6d03-81d2-8004-29cf22baeee7

Data:
{:type :validation,
 :code :referential-integrity,
 :hint "error on validating file referential integrity",
 :file-id #uuid "eb74e0b5-6d03-81d2-8004-29cf22baeee7",
 :details
 [{:code :child-not-found,
   :hint "Child 99121aa4-327a-8008-8004-2c68e7b12d1c not found in parent 05b766be-b93a-8000-8004-2afc564e4725",
   :shape
   ##object[Function]{:id #uuid "05b766be-b93a-8000-8004-2afc564e4725",
                      :name "Inputs",
                      :type :frame,
                      :x 380,
                      :y 978,
                      :width 1124.0000000000002,
                      :height 400,
                      :rotation 0,
                      :selrect ##object[Function]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "eb74e0b5-6d03-81d2-8004-29cf22baeee7",
   :page-id #uuid "eb74e0b5-6d03-81d2-8004-29cf22baeee8",
   :shape-id #uuid "05b766be-b93a-8000-8004-2afc564e4725",
   :args
   {:parent-id #uuid "05b766be-b93a-8000-8004-2afc564e4725", :child-id #uuid "99121aa4-327a-8008-8004-2c68e7b12d1c"}}]}

Trace:
PENPOT.Dh@https://design.penpot.app/js/shared.b130cc40f.js:3468:38
PENPOT.Eh@https://design.penpot.app/js/shared.b130cc40f.js:3468:355
PENPOT.Fh@https://design.penpot.app/js/shared.b130cc40f.js:3468:308
PENPOT.Lx@https://design.penpot.app/js/shared.b130cc40f.js:4409:110
BQa/<@https://design.penpot.app/js/shared.b130cc40f.js:4383:236
u@https://design.penpot.app/js/shared.b130cc40f.js:243:276
r@https://design.penpot.app/js/shared.b130cc40f.js:243:218
d@https://design.penpot.app/js/shared.b130cc40f.js:150:99
next@https://design.penpot.app/js/shared.b130cc40f.js:158:429
next@https://design.penpot.app/js/shared.b130cc40f.js:221:222
d@https://design.penpot.app/js/shared.b130cc40f.js:150:99
next@https://design.penpot.app/js/shared.b130cc40f.js:158:429
next@https://design.penpot.app/js/shared.b130cc40f.js:243:350
d@https://design.penpot.app/js/shared.b130cc40f.js:150:99
next@https://design.penpot.app/js/shared.b130cc40f.js:158:429
next@https://design.penpot.app/js/shared.b130cc40f.js:221:222
d@https://design.penpot.app/js/shared.b130cc40f.js:150:99
next@https://design.penpot.app/js/shared.b130cc40f.js:158:429
shadow$provide[1]/q/</<@https://design.penpot.app/js/shared.b130cc40f.js:151:383


Last events:
[":app.main.data.workspace.thumbnails/assoc-thumbnail"
 ":app.main.data.workspace/workspace-focus-lost"
 ":app.main.data.workspace.undo/check-open-transactions"
 ":app.main.data.workspace.transforms/start-move-selected"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace/copy-selected"
 ":app.main.data.workspace.grid-layout.editor/stop-grid-layout-editing"
 ":app.main.data.workspace.selection/deselect-all"
 ":app.main.data.workspace.selection/handle-area-selection"
 ":app.main.data.workspace/set-margins-selected"
 ":app.main.data.workspace.selection/select-shapes-by-current-selrect"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.selection/update-selrect"
 ":app.main.data.workspace.undo/start-undo-transaction"
 ":app.main.data.workspace.changes/update-indices"
 ":app.main.data.workspace.undo/append-undo"
 ":app.main.data.workspace/paste-shapes"
 ":app.main.data.workspace.changes/commit-changes"
 ":app.main.data.workspace.thumbnails/clear-thumbnail"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shapes"
 ":layout/update"
 ":app.main.data.workspace.undo/start-undo-transaction"
 ":app.main.data.workspace.guides/move-frame-guides"
 ":app.main.data.workspace.comments/move-frame-comment-threads"
 ":app.main.data.workspace.changes/update-indices"
 ":app.main.data.workspace.undo/append-undo"
 ":app.main.data.workspace.changes/update-shapes"
 ":app.main.data.workspace.changes/commit-changes"
 ":app.main.data.workspace.changes/update-shapes"
 ":app.main.data.workspace.modifiers/clear-local-transform"
 ":app.main.data.workspace.undo/commit-undo-transaction"
 ":app.main.data.workspace.modifiers/apply-modifiers"
 ":app.main.data.workspace.shape-layout/update-layout-positions"
 ":app.main.data.workspace.undo/commit-undo-transaction"
 ":app.main.data.workspace/paste-shapes"
 ":app.main.data.workspace/paste-transit"
 ":app.main.data.workspace/paste-from-event"
 ":app.main.data.workspace.texts/update-position-data"
 ":app.main.data.workspace.texts/clean-text-modifier"
 ":app.main.data.workspace.changes/send-update-indices"
 ":app.main.data.workspace.changes/update-shapes"
 ":app.main.data.workspace.texts/commit-position-data"
 ":app.main.data.workspace.thumbnails/request-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.persistence/persist-changes"
 ":app.main.data.workspace.thumbnails/assoc-thumbnail"]
```

### Additional context

The component contains a modifed copy of a component (icon) from Lucide Icons, which is a library dating prior to PenPot 2.0, and which was automatically updated (like other saves).

It might be linked to #4379 , however since I am not sure, I prefered filling a new issue. I am sorry if it is a duplicate.

**Comment by madalenapmelo-kp** [comment]
Hi @Picorims,

Thank you for reporting! You are right, this was indeed related to #4379! We have just released a fix for this and you should no longer experience this behavior, could you please confirm?

**Comment by Picorims** [comment]
Hi @madalenapmelo-kp ,

Unfortunately, I just tried again on the same file (on the online version, as yesterday) and it still happens (content inside the component being moved while the container is fixed in the grid). Same behavior for the undo action as well, the component is moved elsewhere but not deleted. It is hard to tell if the crash is still happening, as it happened after multiple attempts going back and forth to try to get it to work.

Is the fix retroactive, or do I need to re-import the library, or recreate the component ?

If needed, I can send the .penpot file by mail or allow a team member edit access to a copy, if that can help solve the issue.

**Comment by hirunatan** [comment]
@Picorims the fix we made yesterday was related to the crash. Can you tell us if it's still crashing in some cases?

The weird behavior could be not a bug, but a result of the change in how components 2.0 work. As said in #4379, now Penpot doesn't allow to directly modify structure of copies. If you try to drag & drop a layer into a copy, you'll see in the layers panel that it's not put inside the copy but in the root level. For modifying copies this way we have added the new swap function.

Does this solve the issues for you? If not, please send a .penpot file and describe one particular case it's failing. Thanks.

**Comment by Picorims** [comment]
Thank you for the information. From quick tests of yesterday, I couldn't reproduce the crash. However it is hard to tell if it still occurs as I hardly found out the real culprit. If I ever observe that crash again, I will let you know, otherwise I guess the issue can be closed. (It did take a few attempts and was quite unexpected.)

I just have a hard time understanding why the inner content moves while the outer content stay still, while the grid board is not a component, and I am not trying to change the structure intentionally. But I will wait for the tutorials to see if I can find an explanation there, maybe this component was created in a bad way, but this should probably be addressed in the forum and not here. Thanks for the help anyway :) .

**Comment by hirunatan** [comment]
Ok. I close  the issue for now. If you can reproduce a crash later, please open a new issue and give us the specific info.

For the tutorials, we have this one for now https://www.youtube.com/watch?v=dOGu1ke9fM4&t=189s  and you also may find information in Penpot User Guide https://help.penpot.app/user-guide/

Or, indeed, you can ask in the community for more explanations. Thanks to you for using Penpot.

**Comment by Picorims** [comment]
For the record, the dragging behavior can be reproduced with the following .penpot file (inside the zip) :
[grid and components problem.zip](https://github.com/penpot/penpot/files/15016862/grid.and.components.problem.zip)
