### ISSUE TITLE
bug:  Swiching from pen to move points Brakes toolbar

### ISSUE THREAD

**Issue by adambelis** [uxbox/uxbox#4408]
### Steps To Reproduce

1. draw triangle wit pen tool P
2. click on move mode icon in top toolbar (second icon in submenu ) 

### Expected behavior

Swich to move point mode.
toolbar stays in same placethe 

### Actual behavior

switch to move object mode 
toolbar  hides and its impossible to recover

### Screenshots or video

![chrome_TrV4BdYeIm](https://github.com/penpot/penpot/assets/50795097/f7079013-5d2b-4d4a-b61e-866e887ea964)

### Desktop (please complete the following information)

- win10 chrome 

### Additional context

this does not happen if you use shortcuts P and M

**Comment by inanc-g** [comment]
Same issue here, happens on both Firefox (124.0.1) and Chrome (123.0).  
Bug also occurs when trying to set the color of a path.

![image](https://github.com/penpot/penpot/assets/1510491/b333b1f6-4eb9-41a4-8c90-24de29bb63f1)

Found no way to recover the toolbar once it hides other than to restart penpot.

**Comment by madalenapmelo-kp** [comment]
Hi @adambelis and @inanc-g,

Thanks for reporting this! We are already looking into this, you can find more details on this on Taiga here: https://tree.taiga.io/project/penpot/issue/7411

**Comment by madalenapmelo-kp** [comment]
Hi @adambelis,

This issue is now fixed!

**Comment by adambelis** [comment]
@madalenapmelo-kp 
 is that deployed to pen pot website?
 
 i still reproduce this i bug there

**Comment by madalenapmelo-kp** [comment]
Hi @adambelis,

It seems that there are still some persisting edge cases which trigger this behavior so we are reopening this. You can track the issue on Taiga here: https://tree.taiga.io/project/penpot/issue/7776

**Comment by ekidneyrh** [comment]
Hi, this is happening to me on the desktop app. I'm running Fedora 40.

**Comment by imblowfish** [comment]
Hi
I have reproduced the same problem on Chrome
Steps to reproduce:
- Click on `P` hotkey to open pen mode
- Click on `P` again
- Click on `Esc` or `Enter` or any other key to exit pen mode

**Expected**:
You should be able to show toolbar on click
**Actual**:
Toolbar is hidden and you can't show it until page will be reloaded
[Screencast from 2024-10-25 22-25-18.webm](https://github.com/user-attachments/assets/776568c8-fafc-4cb4-b592-dd7a1007c8f3)

**Comment by adambelis** [comment]
i do not repliat this bug anymore

**Comment by adambelis** [comment]
ok but i do replicat this with @imblowfish  steps ... kind of worrying that this is till not fixed

**Comment by madalenapmelo-kp** [comment]
Hi all,

Thanks for reporting that this is still happening! I've added a new bug to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/10566

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be released soon!
