### ISSUE TITLE
bug: Cannot import templates

### ISSUE THREAD

**Issue by lnxredir** [uxbox/uxbox#4573]
### Steps To Reproduce

1. Install via Docker
2. Login/Create an account
3. Try to import a template

### Expected behavior

The template should import normally, all templates are affected by this bug.

### Actual behavior

I get the following error on the web UI:
`There was a problem importing the template. The template wasn't imported.`
On the **penpotapp/backend:latest** it gives me a crash which I believe to be related to JS.

### Environment (please complete the following information)

Self-hosted
Ubuntu Server 22.04
Docker Engine:
```
Client: Docker Engine - Community
 Version:           26.1.1
 API version:       1.45
 Go version:        go1.21.9
 Git commit:        4cf5afa
 Built:             Tue Apr 30 11:47:53 2024
 OS/Arch:           linux/amd64
 Context:           default
```

Docker Compose:
```
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.12
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
```

Docker Containers:
```
CONTAINER ID   IMAGE                       COMMAND                  CREATED        STATUS        PORTS                                                 NAMES
a30c22ec28aa   penpotapp/frontend:latest   "/bin/bash /entrypoi…"   12 hours ago   Up 12 hours   0.0.0.0:9001->80/tcp, :::9001->80/tcp                 penpot-penpot-frontend-1
bbfb5f3bf38d   penpotapp/backend:latest    "/bin/bash run.sh"       12 hours ago   Up 12 hours                                                         penpot-penpot-backend-1
8e7da122a1af   postgres:15                 "docker-entrypoint.s…"   12 hours ago   Up 12 hours   5432/tcp                                              penpot-penpot-postgres-1
327434d7f546   penpotapp/exporter:latest   "node app.js"            12 hours ago   Up 12 hours                                                         penpot-penpot-exporter-1
3677f26130e2   sj26/mailcatcher:latest     "mailcatcher --foreg…"   12 hours ago   Up 12 hours   1025/tcp, 0.0.0.0:1080->1080/tcp, :::1080->1080/tcp   penpot-penpot-mailcatch-1
845791b93d0c   redis:7                     "docker-entrypoint.s…"   12 hours ago   Up 12 hours   6379/tcp                                              penpot-penpot-redis-1
```

### Frontend Stack Trace

```console
192.168.3.2 - - [09/May/2024:15:22:06 +0000] "POST /api/rpc/command/clone-template HTTP/1.1" 200 394 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0"
192.168.3.2 - - [09/May/2024:15:22:33 +0000] "GET /api/rpc/command/get-project-files?project-id=89273e28-46fc-8115-8004-52bfb0675343 HTTP/1.1" 200 33 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0"
192.168.3.2 - - [09/May/2024:15:22:33 +0000] "GET /api/rpc/command/get-team-recent-files?team-id=89273e28-46fc-8115-8004-52bfb0672106 HTTP/1.1" 200 33 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0"
192.168.3.2 - - [09/May/2024:15:22:38 +0000] "POST /api/rpc/command/clone-template HTTP/1.1" 200 394 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0"
```

### Backend Stack Trace

```console
[2024-05-09 15:22:37.474] I app.binfile.v1 - hint="import: started", id="89273e28-46fc-8115-8004-52c0d908b734"
[2024-05-09 15:22:38.497] I app.binfile.v1 - hint="import: terminated", id="89273e28-46fc-8115-8004-52c0d908b734", elapsed="1.020454476s", error?=true
[2024-05-09 15:22:38.499] W app.http.errors - hint="io exception"
SUMMARY:
 →  java.nio.file.AccessDeniedException: /opt/data/assets/29 (UnixException.java:90)
DETAIL:
 →  java.nio.file.AccessDeniedException: /opt/data/assets/29 (UnixException.java:90)
    at: sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438)
        java.nio.file.Files.createDirectory(Files.java:699)
        java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
        java.nio.file.Files.createDirectories(Files.java:793)
        datoteka.fs$create_dir.invokeStatic(fs.clj:331)
        datoteka.fs$create_dir.doInvoke(fs.clj:326)
        clojure.lang.RestFn.invoke(RestFn.java:413)
        app.storage.fs$eval35365$fn__35367.invoke(fs.clj:59)
        clojure.lang.MultiFn.invoke(MultiFn.java:239)
        app.storage$put_object_BANG_.invokeStatic(storage.clj:170)
        app.storage$put_object_BANG_.invoke(storage.clj:161)
        app.binfile.v1$eval48430$fn__48432.invoke(v1.clj:654)
        clojure.lang.MultiFn.invoke(MultiFn.java:229)
        app.binfile.v1$read_import_v1$fn__48026.invoke(v1.clj:493)
        clojure.core$run_BANG_$fn__8906.invoke(core.clj:7849)
        clojure.lang.PersistentVector.reduce(PersistentVector.java:345)
        clojure.core$reduce.invokeStatic(core.clj:6907)
        clojure.core$run_BANG_.invokeStatic(core.clj:7844)
        clojure.core$run_BANG_.invoke(core.clj:7844)
        app.binfile.v1$read_import_v1.invokeStatic(v1.clj:484)
        app.binfile.v1$read_import_v1.invoke(v1.clj:469)
        clojure.lang.AFn.applyToHelper(AFn.java:154)
        clojure.lang.AFn.applyTo(AFn.java:144)
        clojure.core$apply.invokeStatic(core.clj:669)
        clojure.core$apply.invoke(core.clj:662)
        app.db$tx_run_BANG_.invokeStatic(db.clj:543)
        app.db$tx_run_BANG_.doInvoke(db.clj:527)
        clojure.lang.RestFn.invoke(RestFn.java:428)
        app.binfile.v1$eval48057$fn__48058.invoke(v1.clj:505)
        clojure.lang.MultiFn.invoke(MultiFn.java:229)
        app.binfile.v1$read_import_BANG_.invokeStatic(v1.clj:467)
        app.binfile.v1$read_import_BANG_.invoke(v1.clj:449)
        app.binfile.v1$import_files_BANG_.invokeStatic(v1.clj:762)
        app.binfile.v1$import_files_BANG_.invoke(v1.clj:742)
        clojure.core$partial$fn__5922.invoke(core.clj:2647)
        promesa.exec$wrap_bindings$fn__13145.invoke(exec.cljc:192)
        promesa.util.Supplier.get(util.cljc:27)
        java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        java.lang.Thread.run(Thread.java:1583)
```

**Comment by lnxredir** [comment]
Fixed again by adjusting the permission of the **/opt/data/assets** on my host machine, which on my case was **./penpot_assets**
`chmod +755 ./penpot_assets`

I'm starting to assume its not a good idea to run the project as root since it will lack a lot of write permissions, its best to just run the compose file as another user or on a public folder (eg. /var/www/)

**Comment by henri9813** [comment]
I also got the issue.

There is a real subject about user binding.

**Comment by David-Melik** [comment]
Same issue here.
Even when I manage to import it using chmod +755 ./penpot_assets, the font still appears invisible or doesn't render correctly.
