### ISSUE TITLE
bug: design.penpot.app presents a white screen instead of app

### ISSUE THREAD

**Issue by D0-0K** [uxbox/uxbox#6647]
### Steps To Reproduce

Steps to Reproduce:

1. Open https://design.penpot.app
2. page presents with a white screen. (or a white screen with cookies dialog)

### Expected behavior

Expected the loading of the design.penpot.app start page. I've also attempted to load a prototype flow.

### Actual behavior

Opening any link from design.penpot.app leads to a white screen.

If loading without previous cookies, a cookie dialog is shown on top of the white screen,

### Desktop (please complete the following information)

- OS Fedora Linux 42
- Browsers Tested: Firefox 138, Chrome 136, Gnome Web 48.3

### Environment (please complete the following information)

Host: design.penpot.app

### Frontend Stack Trace

```console
design.penpot.app/:41 
            
            
           GET https://design.penpot.app/js/shared.4a9fef12e-1749123469.js net::ERR_ABORTED 404 (Not Found)
index.js?ts=1749124375817:8561 [PLUGINS] Loading plugin system
index.js?ts=1749124375817:4806 SES Removing unpermitted intrinsics
tokens_lib.cljc:336 Uncaught ReferenceError: PENPOT is not defined
(anonymous) @ tokens_lib.cljc:336
(anonymous) @ append.js:3
```

### Backend Stack Trace

```console

```

**Comment by madalenapmelo-kp** [comment]
Hi @D0-0K,

Are you still experiencing this? I haven't been able to reproduce it

**Comment by D0-0K** [comment]
Hi @madalenapmelo-kp, I'm no longer getting the issue on Firefox and Chromium. However Gnome Web and also the community flatpak application I discovered are still affected. I suspect it could be related to the cloudflare detection that happens before the page loads, as this dialog doesn't load at all on Gnome Web and the flatpak. So these perhaps could be getting flagged as bots? More than likely though this could be an issue with cloudflare and not penpot.

**Comment by gmmedia** [comment]
Have the same problem.

The Chrome extension [Harpa](https://chromewebstore.google.com/detail/harpa-ai-ai-automation-ag/eanggfilgoajaocelnaflolkadkeghjp) seems to be the issue.

Errors:
`libs.js?ts=1758621161047:752 Uncaught TypeError: Accessor not expected at intrinsics.%StringPrototype%.replaceAll
l @ libs.js?ts=1758621161047:752
c @ libs.js?ts=1758621161047:752
s @ libs.js?ts=1758621161047:752
l @ libs.js?ts=1758621161047:752
c @ libs.js?ts=1758621161047:752
FIt @ libs.js?ts=1758621161047:752
(anonymous) @ libs.js?ts=1758621161047:779
V1e @ libs.js?ts=1758621161047:777
mSe @ libs.js?ts=1758621161047:779
(anonymous) @ libs.js?ts=1758621161047:779
(anonymous) @ libs.js?ts=1758621161047:780
(anonymous) @ libs.js?ts=1758621161047:909Understand this error
shadow.js.shim.module$rxjs.js:3 Uncaught ReferenceError: shadow$bridge is not defined
(anonymous) @ shadow.js.shim.module$rxjs.js:3
(anonymous) @ append.js:2Understand this error
core.cljc:185 Uncaught u {message: ':malli.core/invalid-schema', data: {…}, cause: null, name: 'Error', description: undefined, …}`

**Comment by bluefinhomeserver** [comment]
Still have this issue. Using Librewolf (So basically, Firefox). Could not use the official Penpot instance ever since i started getting an interest in the project. I have a local setup aswell, but i would love to be on the probably more stable and less Self manager official public instance.

**Comment by niwinz** [comment]
I think the issue was fixed.

**Comment by HardoMX** [comment]
I still get this issue when trying to log in. Using Firefox Developer Edition 151.0b6 on Arch, Windows 11, and NixOS.

The problem does not appear when I use private browsing however.
