### ISSUE TITLE
bug: Internal server error

### ISSUE THREAD

**Issue by keunes** [uxbox/uxbox#7072]
### Steps To Reproduce

1. Go to design.penpot.app in a private browser window

### Expected behavior

Load something

### Actual behavior

Internal error.

### Frontend Stack Trace

```console

```

### Backend Stack Trace

```console

```

### Additional context

[report.txt](https://github.com/user-attachments/files/21603483/report.txt)

**Comment by keunes** [comment]
Now it's back up, although accessing still took a long time. I have a HAR file but can't upload it to GitHub - happy to provide if useful.

**Comment by keunes** [comment]
And then it stopped working again - `get-profile` took a long time to load (see screenshot) and then after a brief flash of my dashboard I get the internal error again:
<img src="https://github.com/user-attachments/assets/07e8c705-ca4e-43fd-a37a-e824e80bdfa3" />

Other times other elements aren't loading (`get-teams`, `push-audit-events`):
<img src="https://github.com/user-attachments/assets/a50ef192-f10b-48d3-83df-6735a24f1f9b" />

**Comment by AbelMSG89** [comment]
I get the internal error too
<img width="1917" height="992" alt="Image" src="https://github.com/user-attachments/assets/c2201844-3103-430d-868b-41292eb3b559" />

<img width="1919" height="1041" alt="Image" src="https://github.com/user-attachments/assets/0b632641-5bce-49c4-84af-209808680244" />

**Comment by Darkziss** [comment]
> I get the internal error too <img alt="Image" width="1917" height="992" src="https://private-user-images.githubusercontent.com/192563645/474639108-c2201844-3103-430d-868b-41292eb3b559.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ0MjEyNTEsIm5iZiI6MTc1NDQyMDk1MSwicGF0aCI6Ii8xOTI1NjM2NDUvNDc0NjM5MTA4LWMyMjAxODQ0LTMxMDMtNDMwZC04NjhiLTQxMjkyZWIzYjU1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgwNVQxOTA5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWM2YzVkMTM2MjY5NjExMWM1OTBmNWVhMzdlMjY0YmU1NjJjMjc0OWM2NjQ1Yzk0YmJiZjIwYTBhZTg1YjAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0l_gVWTAKNCJ_oixlcPxHbXKbPYEL5sEX42jyZlrRdw">
> 
> <img alt="Image" width="1919" height="1041" src="https://private-user-images.githubusercontent.com/192563645/474639633-0b632641-5bce-49c4-84af-209808680244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ0MjEyNTEsIm5iZiI6MTc1NDQyMDk1MSwicGF0aCI6Ii8xOTI1NjM2NDUvNDc0NjM5NjMzLTBiNjMyNjQxLTViY2UtNDljNC04NGFmLTIwOTgwODY4MDI0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgwNVQxOTA5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDFlMjAzMjk0ZGYxMDU2ZDhmNDhmYjRiOGMwNzAxOGZhNWI0MDkxYjdkODI3NjczZWI0NTIzZjI2MDE3MmJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tgln-JwsKKxaM3XWzcT_KvUmyq-H8TsjnFyhapRPGaU">

Same for me

**Comment by Stzyxh** [comment]
There was a  popup when I was editing a design that said something like "update available, pls refresh page." So I refreshed and when I try to open that design I was in I also get the error, but not in other designs. 

I have same log as above

**Comment by kogeletey** [comment]
Also received this error after the last update

**Comment by madalenapmelo-kp** [comment]
Hi everyone,

We are working on a fix for this issue, I'll let you know once we have an update!

**Comment by Darkziss** [comment]
> Hi everyone,
> 
> We are working on a fix for this issue, I'll let you know once we have an update!

Hi, may i know how long it will take?

**Comment by Darkziss** [comment]
> There was a popup when I was editing a design that said something like "update available, pls refresh page." So I refreshed and when I try to open that design I was in I also get the error, but not in other designs.
> 
> I have same log as above

I found a workaround, just duplicate your project through which Penpot was updated

**Comment by madalenapmelo-kp** [comment]
Hi everyone,

The issue should now be fixed, could you clear the cache and let me know if you continue to experience this?

**Comment by Darkziss** [comment]
> Hi everyone,
> 
> The issue should now be fixed, could you clear the cache and let me know if you continue to experience this?

Nothing changed

**Comment by keunes** [comment]
Works again for me (even without emptying cache).
@Darkziss with 'nothing changed' you mean you're still getting the 'internal error'? If so, maybe try again in a private window.

**Comment by Stzyxh** [comment]
Works for me
